### ISSUE TITLE
Not tracking Origin server changes.

### ISSUE THREAD

**Issue by Mat2001mat** [WowzaMediaSystems/wse-plugin-streamresolver#1]
This plugin is absolutely brilliant, thank you.

I'm finding a minor issue though. If I have myStream being run on MediaServerA and then for some reason I stop the stream and move it to MediaServerB, the module doesn't seem to know the origin server has changed.

I'm guessing it's cached it to a list and can't detect the new location. Is there a method to get around this?

Thank you,

Matt

**Comment by rogerlittin** [comment]
Matt,

We are currently working on a fix for this.

Thanks,

Roger.

**Comment by rogerlittin** [comment]
Matt,

The fix has been committed so it should resolve the issue. It is part of a major update so will require that all servers using the module or server listener are updated.

-Roger.

**Comment by Mat2001mat** [comment]
Hi Roger,

You guys are fantastic. Thank you very much!

This is going to solve a lot of problems with my project. 

Matt
