### ISSUE TITLE
ModuleStreamResolver does not resolve origin SMIL files.

### ISSUE THREAD

**Issue by doublefx** [WowzaMediaSystems/wse-plugin-streamresolver#6]
Hi,

I did not manage to make it work with origin SMIL files, I tried:
http://93.93.81.245:1935/chat-jackpotjoy/smil:chat-auto-0.smil/playlist.m3u8
http://93.93.81.245:1935/chat-jackpotjoy/smil:chat-auto-0_all.smil/playlist.m3u8 (because I have a group name)
http://93.93.81.245:1935/chat-jackpotjoy/chat-auto-0.smil/playlist.m3u8

chat-auto-0.smil being present on the origin only, is there a way to make it work?

**Comment by rogerlittin** [comment]
Hi,

As with a regular origin / edge configuration, the smil file does need to be available on the edge.
