### ISSUE TITLE
Dynamic SMIL with DVR

### ISSUE THREAD

**Issue by Mat2001mat** [WowzaMediaSystems/wse-plugin-streamresolver#7]
Hey guys,

I've implemented the following Java Code to dynamically create a SMIL file so that I can use a Wowza Edge with Adaptive BitRate. 
https://www.wowza.com/docs/how-to-use-java-api-calls-to-resolve-smil-file-requests

For non DVR live streams with StreamResolver, this is working really nicely.  However, when I browse to the edge using ?DVR (https://myedgeserver/dvr/amlst:mystream/playlist.m3u8?dvr) I eventually just get a 404. ?DVR works fine if I go directly to the Origin, but I'd love to be able to get this to work with StreamResolver on an Edge. 

I'm really not sure where it's failing.
Would you be able to help?

Many thanks,

Matt

**Comment by akeller** [comment]
Stale, closing.
